
// This file has been generated by the GUI designer. Do not modify.
namespace pingpongproject_ed
{
	public partial class SettingsForm
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pingpongproject_ed.SettingsForm
			global::Stetic.BinContainer.Attach(this);
			this.Name = "pingpongproject_ed.SettingsForm";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
