
// This file has been generated by the GUI designer. Do not modify.
namespace pingpongproject_ed
{
	public partial class MainGame
	{
		private global::Gtk.Fixed fixed2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pingpongproject_ed.MainGame
			this.Name = "pingpongproject_ed.MainGame";
			this.Title = global::Mono.Unix.Catalog.GetString("MainGame");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child pingpongproject_ed.MainGame.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 819;
			this.DefaultHeight = 600;
			this.Show();
		}
	}
}
