
// This file has been generated by the GUI designer. Do not modify.
namespace PingPong_Eduardo
{
	public partial class MainGame
	{
		private global::Gtk.DrawingArea drawingarea1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget PingPong_Eduardo.MainGame
			this.Name = "PingPong_Eduardo.MainGame";
			this.Title = global::Mono.Unix.Catalog.GetString("MainGame");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PingPong_Eduardo.MainGame.Gtk.Container+ContainerChild
			this.drawingarea1 = new global::Gtk.DrawingArea();
			this.drawingarea1.Name = "drawingarea1";
			this.Add(this.drawingarea1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
