
// This file has been generated by the GUI designer. Do not modify.
namespace PongRevenge
{
	public partial class GameMultiplayerWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget PongRevenge.GameMultiplayerWindow
			this.Name = "PongRevenge.GameMultiplayerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("GameMultiplayerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 600;
			this.DefaultHeight = 400;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
