
// This file has been generated by the GUI designer. Do not modify.
namespace PongRevenge
{
	public partial class GameMultiplayerWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PongRevenge.GameMultiplayerWindow
			this.Name = "PongRevenge.GameMultiplayerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("GameMultiplayerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
